# 使用GPU

In [1]:
import torch
from torch import nn

torch.device('cpu'), torch.cuda.device('cuda')

(device(type='cpu'), <torch.cuda.device at 0x1d428879a90>)

查询可用GPU数量

In [2]:
torch.cuda.device_count()

1

这个两个函数允许我们在请求的GPU不存在的情况下运行代码

In [4]:
def try_gpu(i=0):
    """如果存在，则返回gpu(i),否则返回cpu()"""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():
    """返回所有可用的GPU，如果没有GPU，则返回[cpu(),]"""
    devices = [
        torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())
    ]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_all_gpus()

(device(type='cuda', index=0), [device(type='cuda', index=0)])

查询张量所在的设备

In [5]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

存储在GPU上

In [9]:
X = torch.ones(2, 3, device = try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [11]:
Y = x.cuda(0)
X, Y, X+Y

(tensor([[1., 1., 1.],
         [1., 1., 1.]], device='cuda:0'),
 tensor([1, 2, 3], device='cuda:0'),
 tensor([[2., 3., 4.],
         [2., 3., 4.]], device='cuda:0'))

神经网络与GPU

In [13]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())

net(X)

tensor([[-0.0504],
        [-0.0504]], device='cuda:0', grad_fn=<AddmmBackward0>)

确认模型参数存储在同一个GPU上

In [14]:
net[0].weight.data.device

device(type='cuda', index=0)