# 线性代数

## 2.3.1 标量

标量由只有一个元素的张量标识

In [19]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y, x*y, x/y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## 2.3.2 向量

你可以将向量视为标量值组成的列表

In [20]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

通过张量的索引来访问任一元素

In [21]:
x[3]

tensor(3)

访问张量的长度

In [22]:
len(x)

4

只有一个轴的张量，形状只有一个元素

In [23]:
x.shape

torch.Size([4])

## 2.3.3 矩阵

通过指定两个分量m和n来创建一个形状为mxn的矩阵

In [24]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置

In [25]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

## 2.3.4 张量

给定具有相同形状的任何两个张量，任何按元素二元运算的结果都是相同形状的张量。

In [26]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()      # 通过分配新内存，将A的一个副本分配给B
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

## 2.3.5 张量算法的基本性质

两个矩阵按元素乘法称为*哈达玛积*(Hadamard product)

In [27]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [28]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a+X, (a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 2.3.6 降维

计算任意形状张量的元素和

In [29]:
A = torch.arange(20*2, dtype=torch.float32).reshape(2, 5, 4)
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

指定求和汇总张量的轴

In [30]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [31]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

In [32]:
A.sum(axis=[0,1]).shape  # Same as 'A.sum()'

torch.Size([4])

一个与求和相关的量是*平均值*

In [33]:
A.mean(), A.sum()/A.numel()

(tensor(19.5000), tensor(19.5000))

In [35]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

## 2.3.6.1 非降维求和

计算总和或均值时保持轴数不变

In [36]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

通过广播将`A`除以`sum_A`

In [37]:
A / sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

某个轴计算`A`元素的累加求和

In [41]:
A.cumsum(axis=0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

## 2.3.7 点积

点积是相同位置的按元素乘积的和

In [45]:
y = torch.ones(4, dtype=torch.float32)
x = torch.arange(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积

In [46]:
torch.sum(x*y)

tensor(6.)

## 2.3.8 矩阵-向量积

矩阵向量积`Ax`是一个长度为`m`的列向量，其$i^{th}$元素是点积$a_i^{T}x$

In [49]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

## 2.3.9 矩阵-矩阵乘法

我们可以将矩阵-矩阵乘法$AB$看作是简单地执行m次矩阵-向量积，并将结果拼接在一起，形成一个$nXm$矩阵

In [50]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 2.3.10 范数

线性代数中最有用的一些运算符是*范数*(norm)。非正式的说，一个向量的范数告诉我们一个向量有多大。这里考虑的大小概念不涉及维度，而是分量的大小。    
在线性代数中，向量范数是将向量映射到标量的函数$f$。给定任意向量$x$，向量范数要满足一些属性。第一个性质是：如果我们按照常数因子$\alpha$缩放向量的所有元素，其范数也会按相同的常数因子绝对值缩放：
$$
f(\alpha x)=|\alpha|f(x).
$$
第二个性质是我们熟悉的三角不等式：
$$
f(x+y) \leq f(x)+f(y)
$$
第三个性质简单地说范数必须是非负的：
$$
f(x) \geq 0
$$

$L_2$范数是向量元素平方和的平方根

In [51]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

$L_1$范数是向量元素绝对值之和

In [52]:
torch.abs(u).sum()

tensor(7.)

矩阵的*佛罗贝尼乌斯范数*(Frobenius norm)是矩阵元素的平方和的平方根：
$$
||X||_F = \sqrt{\sum_{i=1}^m\sum_{j=1}^nx_{ij}^2} 
$$

In [55]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

### 2.3.10.1 范数和目标

在深度学习中，我们经常试图解决优化问题：*最大化*分配给观测数据的概率；*最小化*预测和真实观测之间的距离。用向量表示物品(如单词、产品和新闻文章)，以便最小化相似项目之间的距离，最大化不同项目之间的距离。目标，或许是深度学习算法中最重要的组成部分(除了数据)，通常被表达为范数。